# Generated by Django 6.1.1 on 2026-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_exchange_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
