# Generated by Django 6.1.1 on 2026-10-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_split_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='university',
        ),
    ]
