# Generated by Django 6.1.1 on 2026-10-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_remove_exchangeprogram_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='places_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
