# Generated by Django 6.1.1 on 2026-10-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_exchangeprogram_places_count'),
    ]

    operations = [
    ]
