# Generated by Django 6.1.1 on 2026-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_places_to_number'),
    ]

    operations = [
        # default потрібен для відкату: без нього SQLite не може відтворити
        # обов'язкову колонку в таблиці, де вже є рядки.
        migrations.AlterField(
            model_name='exchangeprogram',
            name='places',
            field=models.CharField(max_length=50, default=''),
        ),
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='places',
        ),
    ]
