# Generated by Django 6.1.1 on 2026-10-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_places_to_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='places',
        ),
    ]
